### ISSUE TITLE
Missing dependencies when loading quicklisp on its own

### ISSUE THREAD

**Issue by ralt** [quicklisp/quicklisp-client#125]
I have a fairly self-contained scenario where I load quicklisp as a dependency of another project (to use `ql-dist` et al).

My process is the following:
- Load quicklisp in a local folder
- Load all the dependencies of my system in the local quicklisp folder
- Run `buildapp` by pointing to my local quicklisp folder

When using this way, if my system depends on `quicklisp`, I'll get this error when running buildapp:

```
Fatal UNDEFINED-FUNCTION:
  The function QL-SETUP:QMERGE is undefined.
```

I think quicklisp shouldn't depend on the `setup.lisp` file being loaded.

**Comment by quicklisp** [comment]
Quicklisp can't be loaded as a regular ASDF system, sorry. It can only be loaded via its bootstrapping setup.lisp file, which establishes pathnames for Quicklisp to search for stuff.
