### ISSUE TITLE
Problem with CFFI on LWM

### ISSUE THREAD

**Issue by marcoxa** [quicklisp/quicklisp-client#133]
Hi

I have the following problem with CFFI

`CL-USER 11 > (ql:quickload "cffi")

Error: Error while trying to load definition for system cffi from pathname
       /Users/marcoxa/Projects/Lang/CL/quicklisp/dists/quicklisp/software/cffi_0.17.1/cffi.asd:
          (OPERATE (QUOTE TEST-OP) :CFFI-TESTS) does not match (O C).
  1 (continue) Try loading /Users/marcoxa/Projects/Lang/CL/quicklisp/dists/quicklisp/software/cffi_0.17.1/cffi.asd again.
  2 Give up loading /Users/marcoxa/Projects/Lang/CL/quicklisp/dists/quicklisp/software/cffi_0.17.1/cffi.asd.
  3 Try loading another file instead of /Users/marcoxa/Projects/Lang/CL/quicklisp/dists/quicklisp/software/cffi_0.17.1/cffi.asd.
  4 Retry finding system cffi after reinitializing the source-registry.
  5 (abort) Give up on "cffi"
  6 Return to level 0.
  7 Return to top loop level 0.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.
`

It looks like a CFFI problem, but then again, how come it made it into QL?  I tried QL:UNINSTALL "cffi" but it did not change the behavior.

Any idea?

Thanks

Marco

**Comment by marcoxa** [comment]
Just an update.  The `cffi_0.17.1` folder is not present in `software`.

Sorry, but I do not quite understand what is going on.

Any help is appreciated.

Thanks

Marco

**Comment by quicklisp** [comment]
I believe this is because your ASDF is too old. What do you get from `(asdf:asdf-version)`?

**Comment by marcoxa** [comment]
Yep.  2.26.

But I thought QL would update ASDF as well.

Marco

**Comment by quicklisp** [comment]
It does update it - to 2.26. Sometime I'll have it update to 3.x.

I thought LispWorks now ships with ASDF 3? But if it doesn't, you'll need to load ASDF 3 yourself before loading CFFI.

**Comment by marcoxa** [comment]
Loading 3.x fixes the problem.  I was relying on QL to load ASDF.

Thanks.

Marco

On Tue, Jun 7, 2016 at 8:51 AM, Zach Beane <notifications@github.com> wrote:

> It does update it - to 2.26. Sometime I'll have it update to 3.x.
>
> I thought LispWorks now ships with ASDF 3? But if it doesn't, you'll need
> to load ASDF 3 yourself before loading CFFI.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/quicklisp/quicklisp-client/issues/133#issuecomment-224270546>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAfZWkJgULwU15bdrNEmLa2JwIfmorUMks5qJWlMgaJpZM4IvdLz>
> .
>



-- 
Marco Antoniotti
Somewhere over the Rainbow
