### ISSUE TITLE
Over 8x increase in memory consumption when loading Quicklisp 

### ISSUE THREAD

**Issue by otjura** [quicklisp/quicklisp-client#142]
I ran some crude memory usage tests. I have set .sbclrc to start Quicklisp whenever SBCL is started, vanilla quicklisp-quickinstall script, nothing else in .sbclrc. 

Running sbcl loading .sbclrc loading Quicklisp on start, detailed memory usage reports: "The process sbcl (with pid 31997) is using approximately **87.6 MB** of memory."

sbcl --no-userinit (skipping .sbclrc, thus not loading Quicklisp), memory usage report says: "The process sbcl (with pid 31566) is using approximately **10.4 MB** of memory."

I ran that test on and off, always same massive increase in memory use. Anyone else can confirm? Happening on other implementations or just SBCL?

**Comment by quicklisp** [comment]
This is an interesting result. Can you share the code you are using to compute the 87.6 and 10.4 figures?

**Comment by otjura** [comment]
I simply observed KDE's KSysGuard (system monitor) and checked detailed memory information.

**Comment by quicklisp** [comment]
Ok. Well, Quicklisp loads software to do work - that software takes memory. I think you would see a similar size when loading any software. If you find that there is some unusual or weird source of this memory usage, please let me know.
