### ISSUE TITLE
Slow start on arm (raspbian) sbcl

### ISSUE THREAD

**Issue by stacksmith** [quicklisp/quicklisp-client#146]
My arm SBCL installations are consistently slow on startup.  I didn't have much time to dig into it, but I narrowed it down to quicklisp's setup.lisp (3.68 seconds).  Inside, asdf:load-op "quicklisp" takes 2.13 seconds...

I am spoiled by my x86 machines starting up in a blink of an eye... Is the slowness due to the slow microSD storage that is being scanned, or is there a deeper issue?

Thanks

**Comment by quicklisp** [comment]
How fast is loading other software?

**Comment by stacksmith** [comment]
All loads are slower than on my 3GH intel box, but starting up slime is brutally slow. .Especially when working on low-level raspi projects that need to be restarted often..

 What's a good benchmark recipe? Quickloading a largish  system that is not architecture dependent...

**Comment by quicklisp** [comment]
You could try loading mcclim. That's pretty big.

**Comment by stacksmith** [comment]
Gave up on mcclim after 10 minutes...  tried clx instead.

I suppose it's about 10 times slower across the board.

Pi 3, 32-bit raspbian
```
Evaluation took:
  132.154 seconds of real time
  131.220000 seconds of total run time (128.550000 user, 2.670000 system)
  [ Run times consist of 9.010 seconds GC time, and 122.210 seconds non-GC time. ]
```
On my Core I7-2600 3.40GHz
```
Evaluation took:
  11.761 seconds of real time
  11.360000 seconds of total run time (10.952000 user, 0.408000 system)
  [ Run times consist of 1.324 seconds GC time, and 10.036 seconds non-GC time. ]
```

**Comment by quicklisp** [comment]
Ok. I don't think it's specifically Quicklisp startup, then.

**Comment by stacksmith** [comment]
Agreed.  Thanks.
