### ISSUE TITLE
Allow to use a local FASL cache

### ISSUE THREAD

**Issue by phmarek** [quicklisp/quicklisp-client#151]
I see some benefit to have QL check some (local) URL for a cached binary version (FASL-files) before downloading and compiling the sources. Eg. for container/microservices a quick startup is needed (or at least wanted), and doing the compilation in every container is wasteful, takes too long in some cases, and has too many additional dependencies (C compiler, header files, ...).

So, eg. for `(QL :alexandria)`, instead of fetching the sources for `alexandria-20170630-git` some defined URL (`https://my-ql-cache.local/alexandria-20170630-git.tar.gz`) could be tested, and if that exists, its contents would be extracted in `~/.cache/common-lisp/<lisp-implementation>/`. The same can be done for systems with dependencies, I believe.

Such an on-demand download would be _better_ (security, disk space, ...) than having a full-blown container image with _all_ possibly required QL libraries, IMO.

Thank you your kind consideration!

**Comment by quicklisp** [comment]
This sounds interesting and useful, but outside the scope of Quicklisp.
