### ISSUE TITLE
Non-ASCII filenames cause directory scanning problems with SBCL

### ISSUE THREAD

**Issue by metayan** [quicklisp/quicklisp-client#152]
If SBCL is run without UTF-8 support, some files can cause directory scanning to fail:
```sh
touch ~/quicklisp/local-projects/mouse↑.svg
LC_CTYPE=C sbcl --eval "(ql:register-local-projects)"
```
causes
```
debugger invoked on a SB-INT:C-STRING-DECODING-ERROR in thread
#<THREAD "main thread" RUNNING {1001930083}>:
  :ASCII c-string decoding error: the octet sequence #(226) cannot be decoded.
```
One solution is to run SBCL with
`LC_CTYPE=en_US.UTF-8 sbcl`

**Comment by quicklisp** [comment]
This is an SBCL issue, not a Quicklisp issue.

**Comment by metayan** [comment]
The issue was [filed with SBCL](https://bugs.launchpad.net/sbcl/+bug/1737304) and apparently it is the correct behavior from the SBCL point of view.

It would, however, be nice if Quicklisp would catch this error and maybe give a suggestion to start SBCL with ```LC_CTYPE=en_US.UTF-8 sbcl```. I'm quite sure more packages will eventually become available that use non-ASCII filenames, and if someone adds one of those to ```local-projects```, the results are a bit perplexing right now. Especially since it "destroys" ```~/quicklisp/local-projects/system-index.txt```. (It took me quite some time to find the cause, so thought it would be nice to spare others.)

All of this is only relevant if one is starting Emacs+Slime or SBCL in a non-UTF-8 terminal.
