### ISSUE TITLE
Make sources read-only on Emacs

### ISSUE THREAD

**Issue by ruricolist** [quicklisp/quicklisp-client#156]
I just finished "debugging" a problem which turned out to be due to my having accidentally altered a source file in the Quicklisp tree after jumping to a definition with `M-.`. Accordingly, I have a suggestion: make Emacs open files in the Quicklisp tree as read-only by default. This is easily done by adding a `.dir-locals.el` file to the tree containing only:

```
((nil . ((buffer-read-only . t))))
```

Obviously I could just do this for myself, and I have. But everyone is clumsy sometimes, and this particular foot gun need not be left loaded.

**Comment by quicklisp** [comment]
Sorry, I don't like making this the default.
