### ISSUE TITLE
cl-ixf dependencies have been broken since 2017-05-16

### ISSUE THREAD

**Issue by benesch** [quicklisp/quicklisp-client#160]
Quicklisp distributions since 2017-05-16 seem to have an incorrect idea of cl-ixf's dependencies:

```
$ curl -fsSL http://beta.quicklisp.org/dist/quicklisp/2017-04-03/systems.txt | grep cl-ixf
cl-ixf ixf ixf alexandria babel cl-ppcre ieee-floats local-time md5 split-sequence
$ curl -fsSL http://beta.quicklisp.org/dist/quicklisp/2017-05-16/systems.txt | grep cl-ixf
cl-ixf ixf ixf
```

The package hasn't changed in the meantime.

I don't have the slightest idea what to make of this, but it's breaking the way that [quicklisp-homebrew-roundup](http://github.com/benesch/quicklisp-homebrew-roundup) computes dependencies, using `(ql-dist:required-systems (ql-dist:find-system "ixf"))`. Somehow `(ql:quickload "ixf")` still succeeds—perhaps because it's double-checking the ASDF dependencies?

**Comment by xach** [comment]
Thanks for the report. I see it locally, too. I think it may be happening due to how my upload process works. I will look into it further and see what I can do.

Do you know offhand if this happens for other projects as well?

**Comment by benesch** [comment]
> I will look into it further and see what I can do.

🎉 thanks!

> Do you know offhand if this happens for other projects as well?

Afraid not. The only project I ever run quicklisp-homebrew-roundup on is pgloader, and its other dependencies all seem correct.

**Comment by quicklisp** [comment]
The latest dist update should fix this issue, and it should work properly going forward, too.

**Comment by benesch** [comment]
Excellent! Thank you much.
