### ISSUE TITLE
The version of ASDF distributed with Quicklisp is too old.

### ISSUE THREAD

**Issue by j3pic** [quicklisp/quicklisp-client#166]
I ran into trouble building CLOSER-MOP because one of its dependencies uses a feature of ASDF not found in the version shipped with QL. The problem does not affect builds with CL implementations that provide a new enough version, but I've seen this problem using the Ubuntu Trusty version of SBCL (which is version 1.1.14).

**Comment by duncan-bayne** [comment]
I'm having the same problem on Clozure Common Lisp Version 1.11.5/v1.11.5 (LinuxX8664).

```
remote:        ccl now installed        
remote:        Version 1.11.5/v1.11.5  (LinuxX8664)        
...
remote:        ==================================================        
remote:        838 bytes in 0.00 seconds (1389.40KB/sec)        
remote:        ; Fetching #<URL "http://beta.quicklisp.org/client/2017-03-06/quicklisp.tar">        
remote:        ; 250.00KB        
remote:        ==================================================        
remote:        256,000 bytes in 0.00 seconds (54100.84KB/sec)        
remote:        ; Fetching #<URL "http://beta.quicklisp.org/client/2015-09-24/setup.lisp">        
remote:        ; 4.94KB        
remote:        ==================================================        
remote:        5,054 bytes in 0.00 seconds (8658.85KB/sec)        
remote:        ; Fetching #<URL "http://beta.quicklisp.org/asdf/2.26/asdf.lisp">        
remote:        ; 194.07KB        
remote:        ==================================================        
...
remote:        ==================================================        
remote:        218,697 bytes in 0.01 seconds (31551.38KB/sec)        
remote:        ; Loading "hunchentoot"        
remote:        > Error: Error while trying to load definition for system bordeaux-threads from pathname /app/tmp/cache/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.5/bordeaux-threads.asd: You need ASDF >= 3.1 to load this system correctly.        
```

This is preventing me from updating a CCL-based Heroku buildpack to work with the latest Heroku stack and CCL.

**Comment by quicklisp** [comment]
Sorry, Quicklisp will not be distributing a new ASDF any time soon. The version provided with your implementation is the one to use - if it's too old, please follow up with the implementation instead.

**Comment by Hexstream** [comment]
What's preventing Quicklisp from distributing a newer ASDF?

**Comment by j3pic** [comment]
I agree with @Hexstream . Getting all the implementors to shape up is much more difficult than just having the QL installer handle everything. Multiply that difficulty by the difficulty of getting all the Linux distros to distribute the latest versions of everything. My Travis CI test will have to continue explicitly patching ASDF until Ubuntu catches up.

**Comment by Hexstream** [comment]
I see. Thanks for the info.

------------------------

@j3pic Sorry, I could have been clearer. I was merely asking for background information that I was interested in and thought might be of general interest, not contesting the decision. Generally I like to know the "why" of things and appreciate when that is proactively provided, at least in broad strokes.

**Comment by j3pic** [comment]
@xach Thanks for the suggestion. I have added an ASDF 3 `asdf.lisp` to my project and verified that it works.

**Comment by duncan-bayne** [comment]
@quicklisp Thanks for the clarification.  I switched to Roswell for my environment setup in CI, and that pulls down a newer version of ASDF.
