### ISSUE TITLE
Can not downgrade: package http does not exist

### ISSUE THREAD

**Issue by vindarel** [quicklisp/quicklisp-client#174]
Slime 2.22 from the latest Quicklisp dist (august) is broken for me. I tried to downgrade quicklisp, following these instructions: http://blog.quicklisp.org/2011/08/going-back-in-dist-time.html

    (use-package :ql-dist)
    (install-dist "http://beta.quicklisp.org/dist/quicklisp/2018-07-11/distinfo.txt" :replace t)

and I get an error:

```
* (install-dist "http://beta.quicklisp.org/dist/quicklisp/2018-07-11/distinfo.txt" :replace t)

" :replace t)
(ql-dist:install-dist "
* 
debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {10039CE533}>:
  Package HTTP does not exist.

    Stream: #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {10001C21C3}>
```

By the way, the website https://quicklisp.org/, and not https://www.quicklisp.org/beta/ with `www`, points actually to Planet Lisp and it doesn't have a link to QL's website with its documentation, it is a bit annoying.

**Comment by quicklisp** [comment]
I can't reproduce. I think something may have pasted wrong - it looks like it's trying to interpret the URL (with the `http:` prefix) as a symbol.

Can you try putting it in a file and loading the file? And if the file doesn't work, can you paste it in the issue?

**Comment by vindarel** [comment]
Damn, that was it O_o Stupid, but good news. Thank you.

Now to fix my setup, still broken…
