### ISSUE TITLE
GNU CLISP 2.49.93+ (2018-02-18) functions like DELETE-DIR removed

### ISSUE THREAD

**Issue by pupcraft** [quicklisp/quicklisp-client#176]
Actually never mind, it's fixed with this [commit](https://github.com/quicklisp/quicklisp-client/pull/163#issue-180961342). When can we expect the next release?

[see here for discussion and possible fix](https://www.linuxquestions.org/questions/slackware-14/follow-on-re-clisp-re-build-using-current-does-clisp-on-current-work-with-quicklisp-4175627366/)

[change log](https://sourceforge.net/p/clisp/clisp/ci/tip/tree/src/NEWS)

GNU CLISP 2.49.60+ (2017-06-25) works fine from `apt install clisp`
GNU CLISP 2.49.93+ (2018-02-18) this happens:

```
;; Loading file /home/imac/.clisprc.lisp ...  
;;  Loading file /home/imac/install/asdf.lisp ...  
;;  Loaded file /home/imac/install/asdf.lisp  
;;  Loading file /home/imac/quicklisp/setup.lisp ...  
** - Continuable Error  
DEFPACKAGE QL-CLISP: There is no symbol EXT::DELETE-DIR .  
If you continue (by typing 'continue'): This symbol will be created.  
The following restarts are also available:  
RETRY          :R1      Retry compiling #<CL-SOURCE-FILE "quicklisp" "impl">.  
ACCEPT         :R2      Continue, treating compiling #<CL-SOURCE-FILE "quicklisp" "impl"> as having   been successful.  
RETRY          :R3      Retry ASDF operation.  
CLEAR-CONFIGURATION-AND-RETRY :R4 Retry ASDF operation after resetting the configuration.  
RETRY          :R5      Retry ASDF operation. 
CLEAR-CONFIGURATION-AND-RETRY :R6 Retry ASDF operation after resetting the configuration.  
SKIP           :R7      skip (LET # #)  
RETRY          :R8      retry (LET # #)  
STOP           :R9      stop loading file /home/imac/quicklisp/setup.lisp  
SKIP           :R10     skip (LET # #)  
RETRY          :R11     retry (LET # #)  
STOP           :R12     stop loading file /home/imac/.clisprc.lisp  
Break 1 QL-IMPL[3]>    
```

**Comment by c4dr01d** [comment]
I have same issue, I don't know how to solve this error.But in my case, the error is raise at install quicklisp.

**Comment by terminal625** [comment]
This quicklisp [commit](https://github.com/quicklisp/quicklisp-client/commit/957e342a455fee4f8e708c66b8cf25825b19e280) should fix it, but its not released yet.

**Comment by c4dr01d** [comment]
that's latest commit?

**Comment by quicklisp** [comment]
Ok, the new client has been released. A fresh install of quicklisp will get it, and `(ql:update-client)` will fetch it for existing installations.
