### ISSUE TITLE
windows run (ql:quickload 'repl-utilities) error 

### ISSUE THREAD

**Issue by jamesbake** [quicklisp/quicklisp-client#179]
when i used sbcl-1.4.14-x86 to run (ql:quickload 'repl-utilities)  on windows, it goes wrong with error

Unexpected HTTP status for #<URL "http://120.52.51.14/beta.quicklisp.org:80/archive/repl-utilities/2015-06-08/repl-utilities-20150608-git.tgz">: 403

**Comment by jamesbake** [comment]
how can i resolve it ? anyone can help me?

**Comment by jamesbake** [comment]
i found the error in http.lisp when call http-fetch, when the url redirect to new url the variable connect-url is the old value, can you fix with it?

**Comment by jamesbake** [comment]
when ip in url is not the same value

**Comment by quicklisp** [comment]
Is 120.52.51.14 a proxy or something?

**Comment by jamesbake** [comment]
120.52.51.14 is the redirected url, but the domain before redirected is another url just like 99.84.194.71(example), the code is:
(loop
     (when (<= maximum-redirects redirect-count)
       (error 'too-many-redirects
              :url original-url
              :redirect-count redirect-count))
     (with-connection (connection (hostname connect-url) (or (port connect-url) 80))
i think when the loop is not stop, the variable named "url" changed but the "connect-url" is still the old value, so can you fix it and upload it to github?

**Comment by quicklisp** [comment]
Quicklisp does not normally connect to bare IPs - do you know how they came into the request flow in your case? Is it a proxy or something else intercepting and rewriting your traffic?

**Comment by jamesbake** [comment]
Sorry, something happened yesterday,so reply to you so late, i debug it with wireshark, and the ip changed,   i use quicklisp on win7 and i used  anti-virus software, i don't know some programe will intercepted it, but the ip is real changed

**Comment by dbger** [comment]
> 
> 
> Is 120.52.51.14 a proxy or something?

I think it's just a CDN Node IP.

**Comment by quicklisp** [comment]
I think this is a local network issue and there's nothing I can do to fix it, sorry.
