### ISSUE TITLE
System not found: add REGISTER-LOCAL-PROJECTS restart

### ISSUE THREAD

**Issue by phoe** [quicklisp/quicklisp-client#182]
Currently, if a system is not found, the following error is signaled and the following restarts are created:

```
System "qtools-ui-imagetools" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]

Restarts:
 0: [CONTINUE] Try again
 1: [ABORT] Give up on "qtools-ui-imagetools"
 2: [RETRY] Retry SLIME REPL evaluation request.
 3: [*ABORT] Return to SLIME's top level.
 4: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {10117E9E03}>)
```

There should be a convenience `RETRY` restart that calls `(ql:register-local-projects)` and retries the load.

**Comment by phoe** [comment]
(Also, the `CONTINUE` restart probably shouldn't be named `CONTINUE` if its purpose is to `RETRY` - but that's just my nitpicking now.)

**Comment by traut** [comment]
related #172
