### ISSUE TITLE
Please add option for automatic (asdf:disable-output-translations)

### ISSUE THREAD

**Issue by tlikonen** [quicklisp/quicklisp-client#183]
By default ASDF writes `.fasl` files to `~/.cache/common-lisp/...` directory. In some situations I prefer to keep all files inside my program's build directory so I need to load and configure ASDF before loading any systems with Quicklisp:

    (require "asdf")
    (asdf:disable-output-translations)
    (load "quicklisp/setup.lisp")
    (ql:quickload "my-program")

It would be nice if `ql:quickload` had an option for automatically calling `asdf:disable-output-translations` or some other general way of configuring ASDF before writing any .fasl files. It feels ugly to load ASDF manually first because Quicklisp will do that again later.

**Comment by quicklisp** [comment]
* use the `~/quicklisp/asdf-config/init.lisp` config file
* configure asdf after loading quicklisp.
