### ISSUE TITLE
Provide publishing system and central repo

### ISSUE THREAD

**Issue by Risto-Stevcev** [quicklisp/quicklisp-client#188]
I know it would be a large undertaking (I can help) to switch from the curated package list to something like `npm publish`, but I think the move would ultimately lead to much more code churn and overall activity. All major programming languages have something like a central repo that you can publish to, the lack of something similar in CL is severely limiting imo

https://common-lisp.net/project/asdf/asdf/The-defsystem-grammar.html#Version-specifiers-1

**Comment by quicklisp** [comment]
I don't want a system like that. I like things that don't change much. You can try ultralisp instead if you want a different style - maybe it will be more to your tastes.
