### ISSUE TITLE
Feature request: flexible directory tree in bundled packages

### ISSUE THREAD

**Issue by fourier** [quicklisp/quicklisp-client#189]
Current directory tree produced by bundle command is fixed. Suppose one wants to have custom directory layout for the bundled system, i.e.
```
bundle.lisp
system-index.lisp
thirdparty/
      | 
      +--- dependency1/
      +--- dependency2/
software/
      |
      +--- local-project1/
      +--- local-project2/
```
How to achieve it with current bundling ?

**Comment by quicklisp** [comment]
I don't know, sorry.
