### ISSUE TITLE
Error: There is no package named "QL"

### ISSUE THREAD

**Issue by nu8** [quicklisp/quicklisp-client#196]
I am new to Lisp. If I do this:

~~~
C:\ccl> wx86cl.exe -l quicklisp.lisp
? (quicklisp-quickstart:install)
? (quit)
~~~

Then this:

~~~
C:\ccl> wx86cl.exe
? (ql:quickload "dexador")
> Error: There is no package named "QL" .
~~~

How do I get Lisp to remember that I installed QuickLisp?

**Comment by easye** [comment]
Quicklisp will add its loading stanza to your implementation dependent startup file with:
```
(ql:add-to-init-file)
```

**Comment by nu8** [comment]
If thats so, then why was the error produced? Did I install wrong?

**Comment by easye** [comment]
> If thats so, then why was the error produced? Did I install wrong?

You didn't add the Quicklisp loading sequence to your startup sequence.

**Comment by nu8** [comment]
Ok that worked, thank you! I added QuickLisp to the startup. Then I installed
a package, and I wrote this script:

~~~lisp
(ql:quickload "dexador")
(format t "~A"
   (dex:get "http://speedtest.lax.hivelocity.net")
)
(quit)
~~~

but it seems slow:

~~~
$ time wx86cl -l http.lisp
To load "dexador":
  Load 1 ASDF system:
    dexador
; Loading "dexador"
.
<HTML>
<HEAD>
<title> Hivelocity Speedtest Server</title>
</HEAD>
Speedtest files:
<br>
10485760    : <A HREF="../10Mio.dat"> 10Mio.dat</A>
<br>
102400000   : <A HREF="../100mb.file"> 100mb.file</A>
<br>
10737418240 : <A HREF="../10Gio.dat"> 10Gio.dat</A>

</HTML>

real    0m1.550s
~~~

Compare:

~~~
$ time curl speedtest.lax.hivelocity.net
<HEAD>
<title> Hivelocity Speedtest Server</title>
</HEAD>
Speedtest files:
<br>
10485760    : <A HREF="../10Mio.dat"> 10Mio.dat</A>
<br>
102400000   : <A HREF="../100mb.file"> 100mb.file</A>
<br>
10737418240 : <A HREF="../10Gio.dat"> 10Gio.dat</A>

</HTML>

real    0m0.170s
~~~

Am I doing something wrong? Am I installing the package each time instead of
just loading it? If so how do I just load a package instead of installing it?

**Comment by nu8** [comment]
Original issue resolved, I opened a new issue about my other problem, thanks
