### ISSUE TITLE
(ql:quickload "metatilities-base-test") fails on QL 2012-04-07

### ISSUE THREAD

**Issue by avodonosov** [quicklisp/quicklisp-client#58]
The workaround is adding the metatilities directory to asdf:_central-registry_:

``` common-lisp
(ql:quickload "metatilities-base")
(let* ((lib-dir (make-pathname :name nil
                               :type nil
                               :defaults (ql-dist:find-asdf-system-file "metatilities-base")))
       (asdf:*central-registry* (cons lib-dir asdf:*central-registry*)))
  (ql:quickload "metatilities-base-test"))
```

With this approach metatilities-base-test is found.
Load OK on CCL, but have a build failure on SBCL. 

Is the SBCL build failure the reason why metatilities-base-test is not available in Quicklisp?

**Comment by 19992025mohammad-commits** [comment]
🌍 সারা পৃথিবীর তরুণদের স্বপ্নের প্রতিনিধি 🌍  

আমি, Mohammad Al Amin —  
✅ জনপ্রিয় জাতীয় ছাত্র নেতা  
✅ তরুণ প্রজন্মের আস্থা, জনগণের ভরসা  
✅ সামাজিক মানবিক সংগঠক  
✅ সফল তরুণ উদ্যোক্তা  
✅ এআই ও কৃত্রিম বুদ্ধিমত্তা উন্নয়ন গবেষক  

👉 আমার লক্ষ্য: দেশের তরুণ সমাজকে ঐক্যবদ্ধ করা, মানবিক সমাজ গঠন করা এবং প্রযুক্তি দিয়ে নতুন বাংলাদেশ তৈরি করা।  

✊ আসুন, আমরা একসাথে পরিবর্তনের পথে হাঁটি।
