### ISSUE TITLE
Quicklisp doesn't understand the :feature feature of :depends-on

### ISSUE THREAD

**Issue by fare** [quicklisp/quicklisp-client#86]
Since late ASDF 1, :depends-on has recognized a :feature feature, whereby
(:feature <keyword> <system>) means "depend on <system> if the <keyword> is in *features*.

This was broken in ASDF 1, fixed late in ASDF 2, and generalized in ASDF 3 to recognize feature expressions and also work in the top :depends-on of defsystem, as part of the new protocol resolve-dependency-spec / resolve-dependency-combination.

Quicklisp should probably upgrade to ASDF 3 eventually, and call resolve-dependency-spec, or something. It might even specially recognize :feature and record that feature somehow (but then, it might have to notice features defined at runtime within the .asd files, or distinguish feature expressions involving implementation features, etc., so that's probably more complication than wanted).

More generally, the many packages that now constitute ASDF 3 export a lot of hooks that allow to observe or configure the plan traversal, and Quicklisp can probably use these hooks to its benefit.

**Comment by quicklisp** [comment]
Fixed in https://github.com/quicklisp/quicklisp-controller/commit/8edc9e2a.
