### ISSUE TITLE
Rely on ASDF for dependency calculation during ql:quickload?

### ISSUE THREAD

**Issue by avodonosov** [quicklisp/quicklisp-client#88]
Current implementation:

- quicklisp-controller analyzes all ASDF systems when compiling a dist and stores dependency information for every system in systems.txt file.
- during ql:quickload quicklisp-client uses the dependency information from systems.txt to determine list of archives to download.
- there is a protection for the case when quicklisp-contoller calculated dependencies imprecisely: if asdf:missing-dependency is signaled during ql:quickload, then quicklisp-client tries to download that missing dependency.

The problem: another type of dependency calculation error - systems.txt records
a dependency which does not exists, for example, due to issue #86.

 Particular case:

 exscribe.asd has
```common-lisp
   :depends-on ((:feature :exscribe-typeset :cl-typesetting))
```
this means `if *features* contain :exscribe-typeset then we depend on :cl-typesetting`.

But quicklisp-controller thinks that :exscribe-typeset is a dependency, not a feature keyword

In result, ql:quickload sees from systems.txt that exscribe depends on escribe-typeset, tries to determine what archive to download and files with QUICKLISP-CLIENT:SYSTEM-NOT-FOUND: "exscribe-typeset"

A log file for that case: http://cl-test-grid.appspot.com/blob?key=kzn9b4pstf

Possible solution - rely completely on asdf:missing-component to determine required dependencies during ql:quickload. In other words, never fail as long as ASDF is satisfied. If systems.txt says we need a dependency, but the dependency system  does not exist, do not fail until ASDF asks for this dependency.

If ql:quickload relies only on ASDF for dependency calculation, it relaxes the need for  quicklisp-controller to replicate very precisely ASDF logic for dependencies

I suppose the real role of systems.txt is not to determine the dependencies, which is possible by just hooking on asfd:missing-dependency, downloading the dependency and starting over. That way all dependencies will be fetched.

I guess the real role of systems.txt is to print full list of archives to be installed *before* downloading anything. Quicklisp code calls it "load-strategy" and it looks like this:
```
? (ql:quickload :weblocks :prompt t)
To load "weblocks":
  Load 16 ASDF systems:
    alexandria babel bordeaux-threads chunga cl+ssl
    cl-base64 cl-fad cl-ppcre closer-mop flexi-streams
    ironclad metabang-bind puri salza2 trivial-backtrace
    usocket
  Install 23 Quicklisp releases:
    anaphora asdf-system-connections cl-cont cl-containers
    cl-json cl-who f-underscore html-template hunchentoot
    md5 metatilities metatilities-base moptilities
    named-readtables optima parenscript parse-number
    pretty-function rfc2388 split-sequence trivial-timeout
    weblocks weblocks-stores
Press Enter to continue.
```

quicklisp-client could use systems.txt to calculate and print load strategy, but delegate actual dependency traversal to ASDF, and issue warning in case dependency loads initiated by asdf:missing-dependency are different from the load-strategy

Also, as a user I personally never read the load-strategy. For me it would probably be OK if quicklisp fetched dependencies one by one, if that simplifies quicklisp maintenance.

PS
An alternative version of quicklisp-client::autoload-system-and-dependencies which I created while investigating this issue. It does not use load-strategy and only relies on ASDF.
```common-lisp
(defun autoload-system-and-dependencies2 (name &key prompt)
  "Try to load the system named by NAME, automatically loading any
Quicklisp-provided systems when ASDF signals ASDF:MISSING-DEPENDENCY."
  (setf name (string-downcase name))
  (with-simple-restart (abort "Give up on ~S" name)
    (let ((tried-so-far (make-hash-table :test 'equalp)))
      (when (or (not prompt)
                (press-enter-to-continue))
        (tagbody
         retry
         (handler-bind
             (((and asdf:missing-component (not asdf:missing-component-of-version))
               (lambda (c)
                 (let ((missing (asdf::missing-requires c)))
                   (if (gethash missing tried-so-far)
                       (error "Dependency looping -- already tried to load ~
                                 ~A" missing)
                       (setf (gethash missing tried-so-far) missing))
                   (let ((system (find-system (string-downcase missing))))
                     (when system
                       (ensure-installed (release system))
                       (go retry)))))))
           (call-with-macroexpand-progress
            (lambda ()
              (asdf:oos 'asdf:load-op name :verbose nil))))))))
    name)
``

**Comment by quicklisp** [comment]
The :feature problem was fixed in https://github.com/quicklisp/quicklisp-controller/commit/8edc9e2a. I'm not likely to change to use ASDF only any time soon.
